config/routes.rb
Rails.application.routes.draw do
  root to:'cocktails#index'
  resources :cocktails, only: [ :index, :show, :new, :create ] do
    resources :doses, only: [:new, :create, :show]
  end
  resources :doses, only: [:destroy]
end
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  mount_uploader :photo, PhotoUploader
  # has_many :ingredients, :through :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail_id, :scope => [:ingredient_id]
  # validates_uniqueness_of :dose_id, :scope => [:cocktail_id, :ingredient_id,]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end


  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(params[:cocktail_id])
    else
      render :new
    end
  end


  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<div class="banner">
  <div class="banner-content">
    <h1>List of Cocktails</h1>
    <p><strong>Change your life: </strong>learn how to make cocktails</p>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @cocktails.each do |ct| %>
      <div class="col-xs-12 col-sm-4 col-md-3" >
        <%= link_to cocktail_path(ct) do %>
          <div class="cocktail-card">
            <h3><%= ct.name %></h3>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<div class="banner">
  <h1>Add a new cocktail</h1>
</div>
<div class="cocktail-form">
  <div class="col-xs-12 col-sm-4 col-sm-offset-4">
    <%= simple_form_for (@cocktail) do |f| %>
    <%= f.input :name%>
    <%= f.input :photo%>
    <%= f.input :photo_cache, as: :hidden%>
    <%= f.submit "Add a cocktail", class: "btn btn-primary" %>
    <% end %>
    <p><%= link_to "Back to all cocktails", cocktails_path, class: 'btn btn-success' %></p>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner">
  <h1>Info on <%=@cocktail.name %></h1>
</div>
<div class="wrapper">
  <div class="row">
    <div class="col-xs-12 col-sm-3 col-sm-offset-4">
      <div class="ingredient-text">
        <p>List of ingredients</p>
        <ul>
          <%=@cocktail.doses.each do |dose| %>
            <li><%=dose.description%> - <%=dose.ingredient.name%>  | <%= link_to "Delete", dose_path(@cocktail)%> |  </li>
            <%end%>
        <ul>
      </div>
        <div class="ingredient-photo">
          <p>Ingredient Photo</p>
          <%= cl_image_tag @cocktail.photo, height: 300, width: 400, crop: :fill %>
        </div>
      </div>
    </div>
  </div>
</div>
<p><%= link_to "Back to all cocktails", cocktails_path, class: 'btn btn-success' %></p>
<p><%= link_to "Add a dose", new_cocktail_dose_path(@cocktail), class: 'btn btn-success' %></p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<h1>Add a dose</h1>
<%= simple_form_for [@cocktail, @dose] do |f| %>
<%= f.association :ingredient, prompt: "Choose an ingredient"%>
<%= f.input :description %>
<%= f.submit "Add a dose to #{@cocktail.name}", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
      <%= javascript_include_tag "application" %>
      <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer was made with <i class="fas fa-heart"></i> by Alice
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <img src="images/logo.png" alt="logo">
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
  <%= link_to "Add a new cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>


    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="images/final" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li><a href="#">Log Out</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fas fa-bars dropdown-toggle" data-toggle="dropdown" role="button"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Host</a></li>
        <li><a href="#">Trips</a></li>
        <li><a href="#">Messagese</a></li>
      </ul>
    </div>
  </div>
</div>